apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: quay.io/redhat-user-workloads/mcp-lifecycle-operator-tenant/mcp-lifecycle-module-operator-main
  newTag: latest
