apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -fast-1

commonLabels:
  opendatahub.io/config-type: accelerator

commonAnnotations:
  opendatahub.io/fast-version: '1'

resources:
- ../../accelerators
