apiVersion: apps/v1
kind: Deployment
metadata:
  name: maas-controller
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: INFRA_NAMESPACE
          value: "AUTO"
