apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  opendatahub.io/config-type: accelerator

resources:
- nvidia-cuda-config-llm-single-node-template.yaml
- nvidia-cuda-config-llm-single-node-pd-template.yaml
- nvidia-cuda-config-llm-multi-node-template.yaml
- nvidia-cuda-config-llm-multi-node-pd-template.yaml
- amd-rocm-config-llm-template.yaml
- intel-gaudi-config-llm-template.yaml
- ibm-spyre-s390x-config-llm-template.yaml
- ibm-spyre-x86-config-llm-template.yaml
- ibm-spyre-ppc64le-config-llm-template.yaml
