apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  name: kserve-config-llm-single-node-pd-template-nvidia-cuda
  annotations:
    openshift.io/display-name: vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig Single Node P/D (Prefill/Decode)
    openshift.io/description: vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig Single Node P/D (Prefill/Decode) for LLMInferenceService.
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/runtime-version: ""
    # supported-topologies values must be consistent with the samples API and Dashboard usage.
    # See https://github.com/opendatahub-io/odh-model-controller/blob/incubating/server/docs/features/samples/llm-d/llm-d-ui-flow-mechanics.md
    # and https://github.com/opendatahub-io/odh-model-controller/blob/incubating/server/docs/features/llm-d/samples/samples-api.md
    opendatahub.io/supported-topologies: '["workload-single-node-pd"]'
spec:
  template:
    containers:
      - name: main
        image: placeholder
  prefill:
    template:
      containers:
        - name: main
          image: placeholder
