apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -fast-2

commonLabels:
  opendatahub.io/config-type: accelerator

commonAnnotations:
  opendatahub.io/fast-version: '2'

resources:
- ../../accelerators
